### PR TITLE
Enhancements:

### PR DESCRIPTION
**Pull request by bnordli**
* Support multple lines in one query (comma separated)
* Support match on platform prefix (in a separate argument, -pp)
* Handle deviations correctly
* Show journey number with -j argument
* Hide deviations ("Avvik") with -d

### CODE REVIEW

**Comment by ways** [comment]
Hi and thanks.
>    Support multple lines in one query (comma separated)
>    Support match on platform prefix (in a separate argument, -pp)

I'd rather we just make -p match on any length of an argument. So one can use "2" or "2 Retning Majorstuen" or anything in between.

>    Handle deviations correctly

Cool. I'll be adding more deviation info soon.

>    Show journey number with -j argument

Out of curiosity, what would one need this number for?

>    Hide deviations ("Avvik") with -d

**Comment by bnordli** [comment]
Thanks self for having this project!

-p "1" would then match both "1", "11" and "12", so it would be impossible to match only "1" (without resorting to regexp-matching, which becomes quite ugly).

-j is handy for trip planning: "I want to be at stop X by Y, when do I need to leave stop Z?" (assuming a direct line). You can then match the journey number for timely arrival at Z to find the departure time for that journay at X. (Would probably become more helpful if there would be a method to join queries by the command line..)

**Comment by ways** [comment]
Sounds good. But I don't like short arguments (-X) with more than one letter (-XX). Not unixy. =)

So lets just make -p do what you've made -pp do, and drop my old code for -p. If you make the change, I'll merge right away.

**Comment by bnordli** [comment]
Thanks! :)

**Pull request merged**
